name: Cypress tests

on:
  push:
    branches:
      - master
      - feature/login-tests
  pull_request:
    branches: [master]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f Dockerfile.combined -t qa-assignment-sp .

      - name: Run Cypress tests
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/cypress/screenshots:/app/cypress/screenshots" \
            -v "${{ github.workspace }}/cypress/reports:/app/cypress/reports" \
            qa-assignment-sp

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload HTML reports regardless of test status
      - name: Upload Mochawesome report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html
